---
deployment:
  tasks:
    - export REPOPATH=/home/otpotpot/repositories/*
    - export SITEPATH=/home/otpotpot/rina.otpotpotp.of.by/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
